version: '3'

services:
  slurm:
    build: .
    hostname: ernie
    stdin_open: true
    tty: true
    volumes:
      - /Users/masonhsieh/docker-volumes/docker-centos7-slurm/lib:/var/lib/slurmd
      - /Users/masonhsieh/docker-volumes/docker-centos7-slurm/spool:/var/spool/slurmd
      - /Users/masonhsieh/docker-volumes/docker-centos7-slurm/log:/var/log/slurm
      - /Users/masonhsieh/docker-volumes/docker-centos7-slurm/db:/var/lib/mysql
